[package]
name = "winapi_open_process_chimera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.8.1"

[dependencies.winapi]
version = "0.3.9"
features = ["minwindef", "handleapi"]
